FROM golang:1.18
ARG GOLANG_WORK_DIR=/go/src/github.com/pasetlnetwork/pastelup/
WORKDIR ${GOLANG_WORK_DIR}

COPY . .
RUN go mod download
RUN go build .

RUN apt-get update && apt-get install -y git wget curl sudo gnupg2 libgomp1 jq vim
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata

ENV USR_PW="ubuntu"
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1001 ubuntu -p "$(openssl passwd -1 $USR_PW)"

USER ubuntu
WORKDIR /home/ubuntu
